namespace POS.Cashier.AuditTests;

internal static class AuditTestCatalog
{
    public static IReadOnlyList<AuditTestCase> Create() => new AuditTestCase[]
    {
        new("Migration from empty creates current Cashier schema", AuditGroups.Migration, MigrationAuditTests.MigrationFromEmptyCreatesCurrentSchemaAsync),
        new("Approved baseline database upgrades safely", AuditGroups.Migration, MigrationAuditTests.ApprovedBaselineUpgradesSafelyAsync),

        new("Concurrent same-token checkout creates one financial effect", AuditGroups.Concurrency, CashierConcurrencyAuditTests.ConcurrentSameTokenCheckoutCreatesOneEffectAsync),
        new("Concurrent last-stock checkout never creates negative stock", AuditGroups.Concurrency, CashierConcurrencyAuditTests.ConcurrentLastStockCheckoutIsSafeAsync),
        new("Concurrent Gift Voucher redemption succeeds only once", AuditGroups.Concurrency, CashierConcurrencyAuditTests.ConcurrentGiftVoucherRedemptionIsOneTimeAsync),
        new("Concurrent customer-credit checkout cannot exceed limit", AuditGroups.Concurrency, CashierConcurrencyAuditTests.ConcurrentCustomerCreditCannotExceedLimitAsync),
        new("Concurrent customer return cannot over-return", AuditGroups.Concurrency, CashierConcurrencyAuditTests.ConcurrentCustomerReturnCannotOverReturnAsync),
        new("Checkout racing shift close has one valid serial outcome", AuditGroups.Concurrency, CashierConcurrencyAuditTests.CheckoutAndShiftCloseRemainConsistentAsync),

        new("Checkout failure after header staging rolls back everything", AuditGroups.Transaction, CashierControlAuditTests.CheckoutFailureAfterHeaderStagingRollsBackAsync),
        new("Card sale requires a final repository reference", AuditGroups.Control, CashierControlAuditTests.CardSaleRequiresRepositoryReferenceAsync),
        new("Cheque sale requires a final repository reference", AuditGroups.Control, CashierControlAuditTests.ChequeSaleRequiresRepositoryReferenceAsync),
        new("Checkout rejects a stale catalogue price", AuditGroups.Control, CashierControlAuditTests.CheckoutRejectsStaleCataloguePriceAsync),
        new("Price override validates active manager or administrator", AuditGroups.Control, CashierControlAuditTests.PriceOverrideValidatesApproverRoleAsync),
        new("Price override accepts an active manager", AuditGroups.Control, CashierControlAuditTests.PriceOverrideAcceptsActiveManagerAsync),
        new("Float balance excludes sales cash and refunds", AuditGroups.Control, CashierControlAuditTests.FloatBalanceExcludesOperationalCashAsync),
        new("Float Out cannot consume sales cash", AuditGroups.Control, CashierControlAuditTests.FloatOutCannotConsumeSalesCashAsync),
        new("Disabled users cannot authenticate", AuditGroups.Control, CashierControlAuditTests.DisabledUserCannotAuthenticateAsync),
        new("Zero-opening shift and one-open-shift rule are enforced", AuditGroups.Control, CashierControlAuditTests.ZeroOpeningShiftAndSingleOpenShiftAsync),
        new("Stock inquiry returns Stock Item quantities only", AuditGroups.Control, CashierControlAuditTests.StockInquiryReturnsStockItemsOnlyAsync),
        new("Walk-in Wholesale mode persists and validates Wholesale price", AuditGroups.Control, CashierControlAuditTests.WalkInWholesaleModePersistsAsync),
        new("Terminal machine release blocks active work and preserves identity", AuditGroups.Control, CashierControlAuditTests.TerminalReleaseBlocksActiveWorkAndPreservesIdentityAsync),

        new("Cashier utility buttons are wired", AuditGroups.SourcePolicy, SourcePolicyAuditTests.CashierUtilityButtonsAreWiredAsync),
        new("Hidden Credit Note payment placeholder is removed", AuditGroups.SourcePolicy, SourcePolicyAuditTests.HiddenCreditNotePlaceholderIsRemovedAsync),
        new("Cashier Discount Rule entry point is removed while historical snapshots remain", AuditGroups.SourcePolicy, SourcePolicyAuditTests.DiscountRuleEntryPointIsRemovedAsync),
        new("Cashier bottom actions are compact and organized", AuditGroups.SourcePolicy, SourcePolicyAuditTests.CashierBottomPanelIsCompactAndOrganizedAsync),
        new("Cash Payment dialog and shared tender numpad are polished", AuditGroups.SourcePolicy, SourcePolicyAuditTests.CashPaymentDialogAndSharedNumpadArePolishedAsync),
        new("Checkout tender dialogs use the Category 1 transaction family", AuditGroups.SourcePolicy, SourcePolicyAuditTests.CheckoutTenderDialogsUseTransactionFamilyAsync),
        new("Cashier dialogs use controlled owner-aware placement and native chrome", AuditGroups.SourcePolicy, CashierWindowStabilizationSourcePolicyAuditTests.DialogPlacementAndNativeChromeAreControlledAsync),
        new("Cashier repeated submissions and modal closing are guarded", AuditGroups.SourcePolicy, CashierWindowStabilizationSourcePolicyAuditTests.RepeatedSubmissionAndModalCloseAreGuardedAsync),
        new("Float Cash and owned Cashier dialog routes are controlled", AuditGroups.SourcePolicy, CashierWindowStabilizationSourcePolicyAuditTests.FloatCashAndOwnedDialogRoutesAreControlledAsync),
        new("Large Cashier dialogs are responsive and scroll-safe", AuditGroups.SourcePolicy, CashierWindowStabilizationSourcePolicyAuditTests.LargeDialogsAreResponsiveAndScrollableAsync),
        new("Cashier keyboard focus and initial loading are controlled", AuditGroups.SourcePolicy, CashierWindowStabilizationSourcePolicyAuditTests.KeyboardFocusAndSingleInitialLoadAreControlledAsync),
        new("Cashier Scan mode and scanner queue are controlled", AuditGroups.SourcePolicy, CashierKeyboardFlowSourcePolicyAuditTests.ScanModeAndScannerQueueAreControlledAsync),
        new("Cashier keyboard map and fast payment completion are controlled", AuditGroups.SourcePolicy, CashierKeyboardFlowSourcePolicyAuditTests.KeyboardMapAndPaymentCompletionAreControlledAsync),
        new("Cashier processing lock and payment rows are visible", AuditGroups.SourcePolicy, CashierKeyboardFlowSourcePolicyAuditTests.ProcessingLockAndPaymentRowsAreVisibleAsync),
        new("Cashier grid and lookup keyboard flow are readable", AuditGroups.SourcePolicy, CashierKeyboardFlowSourcePolicyAuditTests.GridAndLookupKeyboardFlowAreReadableAsync),
        new("Cashier confirmations and cart recovery are keyboard controlled", AuditGroups.SourcePolicy, CashierKeyboardFlowSourcePolicyAuditTests.ConfirmationAndRecoveryDialogsAreKeyboardControlledAsync),
        new("Cashier Num Lock visibility and modal focus are controlled", AuditGroups.SourcePolicy, CashierKeyboardFlowSourcePolicyAuditTests.NumLockVisibilityAndModalFocusAreControlledAsync),
        new("Transaction and authorization dialogs use the Category 1 family", AuditGroups.SourcePolicy, SourcePolicyAuditTests.TransactionAndAuthorizationDialogsUseCategoryOneFamilyAsync),
        new("Cashier operational windows use the Category 2 family", AuditGroups.SourcePolicy, SourcePolicyAuditTests.OperationalWindowsUseCategoryTwoFamilyAsync),
        new("Cashier summary and control windows use the Category 3 family", AuditGroups.SourcePolicy, SourcePolicyAuditTests.SummaryAndControlWindowsUseCategoryThreeFamilyAsync),
        new("BackOffice repeated navigation and page initialization are reliable", AuditGroups.SourcePolicy, BackOfficeNavigationSourcePolicyAuditTests.NavigationLifecycleIsControlledAsync),
        new("BackOffice navigation and selection styling are organized and readable", AuditGroups.SourcePolicy, BackOfficeNavigationSelectionSourcePolicyAuditTests.NavigationAndSelectionAreOrganizedAsync),
        new("BackOffice purchasing and stock operational controls are wired", AuditGroups.SourcePolicy, BackOfficeOperationalSourcePolicyAuditTests.PurchasingAndStockControlsAreWiredAsync),
        new("Recoverable BackOffice and Cashier UI failures are contained", AuditGroups.SourcePolicy, UiCrashResilienceSourcePolicyAuditTests.RecoverableUiFailuresAreContainedAsync),
        new("Store identity and licence requests are consistent", AuditGroups.SourcePolicy, StoreIdentitySourcePolicyAuditTests.StoreIdentityAndLicenceRequestsAreConsistentAsync),
        new("Licence and terminal responsibilities are separated", AuditGroups.SourcePolicy, LicenseTerminalWorkflowSourcePolicyAuditTests.LicenceAndTerminalResponsibilitiesAreSeparatedAsync),
        new("Item, service, pricing and expiry workflows are explicit", AuditGroups.SourcePolicy, InventoryServiceExpirySourcePolicyAuditTests.InventoryServicePricingAndExpiryWorkflowsAreExplicitAsync),
        new("User-facing quantities are compact and consistent", AuditGroups.SourcePolicy, QuantityDisplaySourcePolicyAuditTests.QuantityDisplayIsCompactAndConsistentAsync),
        new("Item Master matrix and save failures are controlled", AuditGroups.SourcePolicy, ItemMasterSaveSafetySourcePolicyAuditTests.ItemMasterMatrixAndSaveFailuresAreControlledAsync),
        new("Paid In and Paid Out UI do not require manager password", AuditGroups.SourcePolicy, SourcePolicyAuditTests.PaidInAndPaidOutDoNotRequireManagerPasswordAsync),
        new("Below-minimum New Price captures manager identity", AuditGroups.SourcePolicy, SourcePolicyAuditTests.PriceOverrideUiCapturesManagerIdentityAsync),
        new("Checkout failure path writes a technical log", AuditGroups.SourcePolicy, SourcePolicyAuditTests.CheckoutFailurePathWritesTechnicalLogAsync),
        new("Cashier startup enforces licences before login", AuditGroups.SourcePolicy, SourcePolicyAuditTests.StartupEnforcesLicencesBeforeLoginAsync),
        new("Shift restoration preserves original cashier ownership", AuditGroups.SourcePolicy, SourcePolicyAuditTests.ShiftRestorationPreservesCashierOwnershipAsync),
        new("Sale commits before receipt printer and drawer actions", AuditGroups.SourcePolicy, SourcePolicyAuditTests.SaleCommitsBeforeHardwareActionsAsync),
        new("Cashier lock screen has audited Manager recovery and safe exit", AuditGroups.SourcePolicy, LockRecoverySourcePolicyAuditTests.ManagerRecoveryAndSafeExitAreControlledAsync),
        new("Phase 11A dual database-provider foundation is controlled", AuditGroups.SourcePolicy, DatabaseFoundationSourcePolicyAuditTests.DualProviderFoundationIsControlledAsync),
        new("POS Network SQL Server setup and migration path is controlled", AuditGroups.SourcePolicy, SqlServerMigrationSourcePolicyAuditTests.DedicatedSqlServerBaselineIsControlledAsync),
        new("SQL Server operational text collations are controlled", AuditGroups.SourcePolicy, SqlServerCollationSourcePolicyAuditTests.OperationalTextCollationsAreControlledAsync),
        new("Production deployment and recovery are controlled", AuditGroups.SourcePolicy, ProductionDeploymentSourcePolicyAuditTests.ProductionDeploymentIsControlledAsync),
        new("Store connection recovery and network resilience are controlled", AuditGroups.SourcePolicy, ConnectionResilienceSourcePolicyAuditTests.StoreConnectionRecoveryIsControlledAsync),
        new("Production setup upgrade repair and wizard layout are controlled", AuditGroups.SourcePolicy, SetupUpgradeRepairSourcePolicyAuditTests.SetupUpgradeRepairAndWizardLayoutAreControlledAsync),
        new("Cashier licence recovery and installed upgrades are controlled", AuditGroups.SourcePolicy, LicenseRecoverySourcePolicyAuditTests.CashierLicenceRecoveryAndUpgradeAreControlledAsync),
        new("Release version and database backup modes are controlled", AuditGroups.SourcePolicy, ReleaseReadinessSourcePolicyAuditTests.ReleaseVersionAndBackupModesAreControlledAsync),
        new("Live POS database path is never an audit database", AuditGroups.SourcePolicy, SourcePolicyAuditTests.LiveDatabasePathIsExcludedAsync)
    };
}
