namespace POS.Core.Services.Licensing
{
    // Generated by the private POS License Generator.
    // This file contains only the public verification key.
    public static class LicensePublicKey
    {
        public const string KeyId = "POS-8B9A4B7173240A6A";

        public const string PublicKeyPem =
            "-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAvvUuROYlhB+12YzT8xxk\nIDxIh1EE6LAkKkHLPHKxEGNAeicoCvQSzC9tEpH3WJWBbJs65fSGvISheHaoGUCu\nOVFDIG+TX8SESeEP/6ljWi2ZOMlzWkea0J23dVeKHHi0GuT4QxySYAabPSasWoQz\nZTH4ZGbhrgpnJRa0VNDZoSHhG5bl3gwymzPGUq/XZtFWCzawK0D/OdlKdATioNoE\nDIZ8GU24fFF30B3kdU3faoD8ARi9isT069h7km2GIw6ahzG8+pz+MMM8XCUOyVp3\nAVFLGvgpVeSWZQ3f7CmHqwNgoOaM9PGbNzPvfP/EqjLaufXgLE3KrMvfWmPPa19N\nUIzL8HFXBDtJ7oZaQpkCIYXj/IFUIjV6RUaUGn6crfmcWrG7jzBkavMgxBlZC21H\ndsSKXLKjxd6de0RyvwGCVckUR3cyUiRAmAfMDULeCYsWfrmybJDD3W9wUJaMlsht\nW38hPcwbQmeBKJ2jvLkTqeJ22b4tuNtBFQm3hGAxafNdAgMBAAE=\n-----END PUBLIC KEY-----";
    }
}
