using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace POS.Core.Models.Licensing
{
    public class LicenseDocument
    {
        public string LicenseId { get; set; } = string.Empty;

        [JsonConverter(typeof(JsonStringEnumConverter))]
        public LicenseType LicenseType { get; set; }

        public string StoreId { get; set; } = string.Empty;

        public string StoreName { get; set; } = string.Empty;

        // For store license, this can be empty.
        // For terminal license, this should be "01", "02", etc.
        public string TerminalNo { get; set; } = string.Empty;

        // For store license, this can be empty.
        // For terminal license, this should match the current PC machine code.
        public string MachineCode { get; set; } = string.Empty;

        public DateTime IssuedOn { get; set; }

        public DateTime ExpiresOn { get; set; }

        public int GraceDays { get; set; } = 7;

        public List<string> AllowedModules { get; set; } = new();

        // Digital signature generated by your private license generator.
        public string Signature { get; set; } = string.Empty;

        public bool IsStoreLicense => LicenseType == LicenseType.StoreLicense;

        public bool IsTerminalLicense => LicenseType == LicenseType.TerminalLicense;
    }
}